language: node_js
node_js:
  - '8'
cache:
  pip: true
  npm: true
  directories:
    - "/home/travis/.rvm/"
    - node_modules
    - "$(npm config get prefix)/lib/node_modules/firebase-tools"
script:
  - echo "Deploy!!"
  - pushd functions
  - npm i
  - popd
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
#  - ./line.sh

